appname: tutorial-backend

replicaCount: 1

image:
  name: acrtutorialazasse001.azurecr.io/tutorial-backend

envVar:
  name: "MONGODB_CONNECTION_STRING"

service:
  type: LoadBalancer
  port: 8089
  targetPort: 8089
