name: DEV - Tutorial Backend Deploy

on:
  repository_dispatch:
    types: [tutorial-backend-cd-dev]
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  CLUSTER_NAME: aks-tutorial-az-asse-001
  CLUSTER_RESOURCE_GROUP: rg-tutorial-cicd-lab
  NAMESPACE_PREFIX: tutorial
  PROJECT_NAME: tutorial
  MICROSERVICE_NAME: tutorial-frontend
  TAG: '0.0.1-SNAPSHOT'


jobs:
  deploy-microservice:
    name: Deploy Microservice
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: http://dev-example.appgw.cf/node-express/books

    steps:
      - name: Checkout pipelines
        uses: actions/checkout@v2

      - name: List working directory
        run: ls

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Set Kubernetes Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_RBAC_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: 'Build Deployment Template'
        run: |
          helm template ./helm/apptemplate \
          --namespace ${{ env.NAMESPACE_PREFIX }}-${{ env.ENVIRONMENT }} \
          --set appname=${{ env.MICROSERVICE_NAME }} \
          --set env=${{ env.ENVIRONMENT }} \
          --set image.name=acrtutorialazasse001.azurecr.io/${{ env.MICROSERVICE_NAME }} \
          --set image.tag=${{ env.TAG }} \
          --set envVar.name=VUE_APP_ENPOINT_API_BACKEND \
          --set envVar.value=http://20.43.159.232:8089/api/ \
          --set service.port=80 \
          --set ingress.enabled=true \
          --set ingress.dns=584d9c19d32846c3b161.southeastasia.aksapp.io \
          --set buildNumber=${{ github.run_number }} \
          --output-dir helm/output
     
      - name: 'Deploy'
        run: |
          export KUBERNETES_NAMESPACE=${{ env.NAMESPACE_PREFIX }}-${{ env.ENVIRONMENT }}
          kubectl apply -f helm/output/apptemplate/templates/deployment.yaml -n ${KUBERNETES_NAMESPACE}
          kubectl apply -f helm/output/apptemplate/templates/service.yaml -n ${KUBERNETES_NAMESPACE}
          kubectl apply -f helm/output/apptemplate/templates/ingress.yaml -n ${KUBERNETES_NAMESPACE}