name: DEV - MongoDB Deploy

on:
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  CLUSTER_NAME: aks-tutorial-az-asse-001
  CLUSTER_RESOURCE_GROUP: rg-tutorial-cicd-lab
  NAMESPACE_PREFIX: tutorial
  PROJECT_NAME: tutorial
  MICROSERVICE_NAME: db
  TAG: 'latest'


jobs:
  deploy-microservice:
    name: Deploy Microservice
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout pipelines
        uses: actions/checkout@v2

      - name: List working directory
        run: ls

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Set Kubernetes Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_RBAC_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: 'Build Deployment Template'
        run: |
          helm template ./helm/apptemplate \
          --values helm/apptemplate/${{ env.PROJECT_NAME }}/${{ env.MICROSERVICE_NAME }}.yaml \
          --namespace ${{ env.NAMESPACE_PREFIX }}-${{ env.ENVIRONMENT }} \
          --set appname=${{ env.MICROSERVICE_NAME }} \
          --set env=${{ env.ENVIRONMENT }} \
          --set image.tag=${{ env.TAG }} \
          --set envVar.value=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} \
          --set envVar.value2=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} \
          --output-dir helm/output
     
      - name: 'Deploy'
        run: |
          export KUBERNETES_NAMESPACE=${{ env.NAMESPACE_PREFIX }}-${{ env.ENVIRONMENT }}
          kubectl apply -f helm/output/apptemplate/templates/deployment.yaml -n ${KUBERNETES_NAMESPACE}
          kubectl apply -f helm/output/apptemplate/templates/service.yaml -n ${KUBERNETES_NAMESPACE}